name = "BenEStock"
uuid = "92807377-c9bd-41ba-b36e-d8468569083a"
authors = ["Paul Leiby <pleiby@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
